[toolchain]
channel = "nightly-2022-08-03"
components = ["cargo", "rust-docs", "rust-src", "rust-std", "rustc", "rustfmt"]
targets = ["aarch64-unknown-linux-musl", "x86_64-apple-darwin", "x86_64-unknown-linux-musl"]
profile = "minimal"
